# Generated by Django 4.1.2 on 2022-10-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_delete_profile_customeuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='bio',
            field=models.CharField(default="I'm best fighter in the world", max_length=200),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
