# Generated by Django 4.1.2 on 2022-10-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_customeuser_age_customeuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='all_fighting',
            field=models.IntegerField(default=0),
        ),
    ]
