# Generated by Django 4.1.2 on 2022-10-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_customeuser_all_fighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='defeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='victory',
            field=models.IntegerField(default=0),
        ),
    ]
