# Generated by Django 4.1.2 on 2022-10-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='player_left',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='battle',
            name='riavl_right',
            field=models.IntegerField(default=2),
        ),
    ]
