# Generated by Django 4.1.2 on 2022-10-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_battle_player_left_battle_riavl_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle_tic_tacoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_player', models.CharField(max_length=50)),
                ('second_player', models.CharField(max_length=50)),
                ('rival_turn', models.BooleanField(default=False)),
                ('player_turn', models.BooleanField(default=False)),
                ('rival_winner', models.BooleanField(default=False)),
                ('player_winner', models.BooleanField(default=False)),
            ],
        ),
    ]
