# Generated by Django 4.1.2 on 2022-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_battle_tic_tacoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_1',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_2',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_3',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_4',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_5',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_6',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_7',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_8',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle_tic_tacoe',
            name='box_9',
            field=models.CharField(default=21, max_length=10),
            preserve_default=False,
        ),
    ]
